## The LU decomposition in python

The routines to compute the A=PLU factorization are in the scipy library. See [lu_factor](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_factor.html#scipy.linalg.lu_factor) and [lu_solve](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lu_solve.html#scipy.linalg.lu_solve).


In [1]:
import numpy as np
import scipy.linalg as la
import matplotlib.pyplot as plt

Start with the matrix
$$
A=\begin{bmatrix}
3&2&3\\1&1&1\\1&0&1\\
\end{bmatrix}
$$
and run lu_factor:

In [2]:
A = np.array([[3,2,3], [1,1,1], [1,0,1]])
lu, piv = la.lu_factor(A)

<ipython-input-2-02a1565b5c8a>:2: LinAlgWarning: Diagonal number 3 is exactly zero. Singular matrix.
  lu, piv = la.lu_factor(A)


**QUESTION 1**: Read the documentation and explain how to recover $A$ from the output of lu_factor(A). Illustrate with the example $A=\begin{bmatrix}
3&2&3\\1&1&1\\1&0&1\\
\end{bmatrix}$.


First extract the lower and upper triangular matrices $L$ and $U$ from `lu` output (add the identity to the lower triangular matrix to obtain the correct form). Then, multiply them to get $LU$ and finally permute by `piv` to get back $A$.

In [5]:
A = np.array([
    [3, 2, 3],
    [3, 1, 1],
    [1, 0, 1]
])

lu, piv = la.lu_factor(A)
L = np.tril(lu, k=-1) + np.eye(3)
U = np.triu(lu)
result = (L @ U)[piv]
print(result)

[[3. 2. 3.]
 [3. 1. 1.]
 [1. 0. 1.]]


**QUESTION 2**: To solve $Ax=b$ we can use either of the following.

1) x = la.solve(A, b)
2) lu, piv = la.lu_factor(A); x = la.lu_solve((lu,piv),b)

Compare the time it takes to run (1) and (2) when A and b are large random matrices/vectors. Use np.random.rand(N,N) to obtain matrices whose entries are uniformly distributed on $[0,1]$.

The second method takes about $40\%$ less time to complete. The majority of this time is for computing the $PLU$ decomposition.

In [7]:
N = 3000
A = np.random.rand(N, N)
b = np.random.rand(N)

%time x = la.solve(A, b)
%time lup = la.lu_factor(A)
%time lup = la.lu_factor(A); x = la.lu_solve(lup, b)

Wall time: 391 ms
Wall time: 289 ms
Wall time: 293 ms
